id-url = "http://www.hgamer3d.org/component/HG3DEngineGio.0517"
description = "HGamer3D fresco component which delivers the C++ binding towards the Urho3D engine."
license-short = "Apache 2.0 License"
signing-key = "https://www.github.com/urs-of-the-backwoods.keys"

[[implementation]]
  architecture = "amd64"
  operating-system = "windows"
  archive-download-location = "http://www.hgamer3d.org/downloads/gamegio-amd64-windows-2.0.0.tar.gz"

[[implementation.dependency]]
  id-url = "http://www.hgamer3d.org/tools/Urho3D-1.6"
  environment-settings = ["add-path PATH ./bin"]

[[implementation]]
  architecture = "amd64"
  operating-system = "linux"
  archive-download-location = "http://www.hgamer3d.org/downloads/gamegio-amd64-linux-2.0.0.tar.gz"

[[implementation.dependency]]
  id-url = "http://www.hgamer3d.org/tools/Urho3D-1.6"
  environment-settings = ["add-path LD_LIBRARY_PATH ./bin"]

[[implementation]]
  architecture = "amd64"
  operating-system = "darwin"
  archive-download-location = "http://www.hgamer3d.org/downloads/gamegio-amd64-darwin-2.0.0.tar.gz"

[[implementation.dependency]]
  id-url = "http://www.hgamer3d.org/tools/Urho3D-1.6"
  environment-settings = ["add-path LD_LIBRARY_PATH ./bin"]

license-full = '''
Copyright 2016 Peter Althainz

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'''